### ISSUE TITLE
unknown error: Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by aijanai** [jciolek/docker-protractor-headless#10]
Hi,

I can't start Google Chrome 55.0.2883.87  in my Linux Jenkins server (which is, needless to say, headless) with your docker image.
The integral error is:

```
jenkins@ip-172-30-2-185:~/wd-funnel-checker$ docker run -it --privileged --rm --net=host -v /dev/shm:/dev/shm -v $(pwd):/protractor webnicer/protractor-headless protractor-mobile-conf.js --suite mobile --params.homepage=https://www.wanderio.com/it
(node:22) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[09:31:07] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[09:31:07] I/launcher - Running 1 instances of WebDriver
[09:32:07] E/launcher - unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 3.13.0-103-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.06 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'ip-172-30-2-185', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-103-generic', java.version: '1.7.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
[09:32:07] E/launcher - WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 3.13.0-103-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.06 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'ip-172-30-2-185', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-103-generic', java.version: '1.7.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:198:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[09:32:07] E/launcher - Process exited with error code 199
```

Here is protractor-mobile-conf.js content:

```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  suites:{
    mobile: 'checkMobile.js',
  },
  capabilities: {

    'browserName': 'chrome',
    'chromeOptions': {
      'args': ['user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 8_0_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Chrome/55.0 Mobile/12A405 Safari/600.1.4']
    }

    /*
    'browserName': 'phantomjs',
    'phantomjs.page.settings.userAgent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12A405 Safari/600.1.4',
    'phantomjs.binary.path': require('phantomjs-prebuilt').path,
    'phantomjs.ghostdriver.cli.args': ['--loglevel=DEBUG']
    */
  },
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 60000,
    isVerbose: true,
    print: () => {}
  },
  params: {
    homepage: 'https://www.wanderio.com/it'
  },
  onPrepare: function() {
    var SpecReporter = require('jasmine-spec-reporter');
    jasmine.getEnv().addReporter(new SpecReporter({displayStacktrace: 'summary'}));
  }
}
```

Here is an excerpt of my top command after I run protractor through your image:

```
22245 root      20   0  199292   2088   1492 S   0,0  0,0   0:00.00          `- docker-containerd-shim 2cf65b1ad0949c37c2d39e8781a1161cca9200987c0768267885a043e711692f /var/run/docker/libcontainerd/2cf65b1ad094+ 
22259 root      20   0   20044   1484   1216 S   0,0  0,0   0:00.00              `- /bin/bash /protractor.sh protractor-mobile-conf.js --suite mobile --params.homepage=https://www.wanderio.com/it                 
22271 root      20   0    4328    708    592 S   0,0  0,0   0:00.00                  `- /bin/sh /usr/bin/xvfb-run -a --server-args=-screen 0 1280x1024x24 protractor protractor-mobile-conf.js --suite mobile --pa+ 
22285 root      20   0  172388  18676   8092 S   0,0  0,2   0:00.01                      `- Xvfb :99 -screen 0 1280x1024x24 -nolisten tcp -auth /tmp/xvfb-run.fi6mvp/Xauthority                                     
22290 root      20   0  990180  32648  11864 S   0,0  0,4   0:00.31                      `- node /usr/local/bin/protractor protractor-mobile-conf.js --suite mobile --params.homepage=https://www.wanderio.com/it  
[..]
 6490 jenkins   20   0   25776    292    108 S   0,0  0,0   1:04.87  `- SCREEN -d -m webdriver-manager start                                                                                                        
 6491 jenkins   20   0  888600      0      0 S   0,0  0,0   0:00.33      `- node /var/lib/jenkins/wd-funnel-checker/node_modules/.bin//webdriver-manager start                                                      
 6507 jenkins   20   0 3485988 220036   5072 S   0,0  2,7  26:07.44          `- java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/var/lib/jenkins/wd-funnel-checker/node_modules/protracto+ 
22303 jenkins   20   0  135100   7860   5912 S   1,0  0,1   0:00.23              `- /var/lib/jenkins/wd-funnel-checker/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25 --port=21+ 
22309 jenkins   20   0       0      0      0 Z   0,0  0,0   0:00.02                  `- [chrome] <defunct>                     
```

I wasn't successful in running locally Xvfb too, I have to admit.

What am I doing wrong?
Thanks for any support you can provide about it

**Comment by jciolek** [comment]
Hi @aijanai 

Thanks a lot for using my image!

Having looked at the randomly appearing errors for different people I came to a conclusion that we need to lock down certain versions of the dependencies, so that we know which versions of node, protractor, webdriver and chrome are actually being used. I have been thinking awhile about the proper solution and so far could not come up with anything better than a tagging system which gives all of that information at a glance.

~~Could you please try the following tag: v1.0.0_c54_n6.9.1_p4.0.14_w2.27~~

~~I know it's a mouthful, but at least it is clear what is what:~~

~~- v1.0.0 - the version of the Dockerfile for this configuration~~
~~- c54 - Chrome 54~~
~~- n6.9.1 - node 6.9.1~~
~~- p4.0.14 - protractor 4.0.14~~
~~- w2.27 - webdriver 2.27~~

Please do let me know how it goes.

Cheers,
Jacek

**Edit**
You can safely try the tag "latest" or "chrome54".

I have abandoned the idea of the terrible tag I mentioned above.

Jacek

**Comment by jciolek** [comment]
Hi @aijanai, I have pinned the Chrome to version 55 and chromedriver to version 2.27 and they appear to be working together. I am closing this issue, if you experience same problems, please re-open.

**Comment by qualityshepherd** [comment]
Yes, Chrome 55 and chromedriver 2.27 work fine together. But I get this error every time on Ubuntu 16, chrome 58, and chromedriver 29. Just fyi...
