### ISSUE TITLE
unknown error: Chrome failed to start: crashed

### ISSUE THREAD

**Issue by momoko8443** [jciolek/docker-protractor-headless#18]
Hi, Jciolek
When I ran shell "sh ./protractor.sh protractor-conf.js", some errors threw.
protractor-conf.js is the default file in angular.io (v1.6.1), 
but it works well when I run "protactor protactor-conf.js" on my host machine directly.  

`
[04:03:01] I/direct - Using ChromeDriver directly...
[04:03:01] I/launcher - Running 1 instances of WebDriver
[04:04:01] E/launcher - unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.9.13-moby x86_64)
[04:04:01] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.9.13-moby x86_64)
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/direct.js:70:26)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:198:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[04:04:01] E/launcher - Process exited with error code 199
`

**Comment by momoko8443** [comment]
I remove protractor.sh from angular.io, now spec runs, but new exception threw.
[18:30:01] E/protractor - Could not find Angular on page http://localhost:8000/e2e/fixtures/anchor-scroll/ : retries looking for angular exceeded
F[18:30:11] E/protractor - Could not find Angular on page http://localhost:8000/e2e/fixtures/anchor-scroll-y-offset/ : retries looking for angular exceeded
F[18:30:21] E/protractor - Could not find Angular on page http://localhost:8000/e2e/fixtures/anchor-scroll-y-offset/ : retries looking for angular exceeded

**Comment by momoko8443** [comment]
I run the docker container successfully on my macbook host machine, but it doesn't work on CentOS...still reports
E/launcher - unknown error: Chrome failed to start: crashed

**Comment by firehist** [comment]
Hey here.
We got the same pbm on a debian 8!

```[22:41:51] I/direct - Using ChromeDriver directly...
[22:41:51] I/launcher - Running 1 instances of WebDriver
[22:42:51] E/launcher - unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.16.0-4-amd64 x86_64)
[22:42:51] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 3.16.0-4-amd64 x86_64)
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/direct.js:70:26)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:198:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[22:42:51] E/launcher - Process exited with error code 199
```

**Comment by jciolek** [comment]
Hey guys,

Does this problem persist on the latest image?

**Comment by asidarovich** [comment]
@jciolek @momoko8443 @firehist Has anyone resolved the issue?

**Comment by sorx00** [comment]
Same problem on Debian 9.
Any suggestions?

**Comment by timnederhoff** [comment]
Same here, CentOS 7 + Docker 17.03

**Comment by sorx00** [comment]
Well, I deleted option `seleniumAddress` and set `directConnect: true`. It is works for me now.

**Comment by jciolek** [comment]
Thanks @sorx00 

I guess I can close this now.

**Comment by momoko8443** [comment]
Actually, I've used native selenium + headless chrome to write an AT framework for angular.
