### ISSUE TITLE
E/configParser - Error code: 105

### ISSUE THREAD

**Issue by suswari** [jciolek/docker-protractor-headless#39]
Hi
I wanted to run dockerised protractor tests and tried webnicer. When i execute the following command: docker run -i --privileged --rm --net=host -v /dev/shm:/dev/shm -v ${pwd}:protractor webnicer/protractor-headless typeScript/config/config.js . I see the following error

sudo: unable to resolve host linuxkit-025000000001
[15:16:41] E/configParser - Error code: 105
[15:16:41] E/configParser - Error message: failed loading configuration file typeScript/config/config.js
[15:16:41] E/configParser - Error: Cannot find module '/protractor/typeScript/config/config.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at ConfigParser.addFileConfig (/usr/local/lib/node_modules/protractor/built/configParser.js:125:26)
    at Object.initFn [as init] (/usr/local/lib/node_modules/protractor/built/launcher.js:93:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/protractor/built/cli.js:112:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

Can you please help me resolving the issue. Thanks much!!

**Comment by jensklose** [comment]
Seems to be multiple issues.
First give us more informations about your environment, please.
Next there is a typo in your command, but your error message don't spot this. It should be something like:
```
docker: Error response from daemon: invalid volume specification: '...:protractor': invalid mount config for type "bind": invalid mount path: 'protractor' mount path must be absolute.
```

**Comment by suswari** [comment]
HI @jensklose,
  I figured out that the the directory _protractor_ isn't created with the docker command I ran. So I added mkdir protractor command to the docker file. Then that worked. Thanks much for your response. Appreciate it!!

**Comment by jciolek** [comment]
Hi @suswari 

From what you posted I can see that you specified `-v ${pwd}:protractor` instead of `-v ${pwd}:/protractor`, hence the problem. You shouldn't need to add `mkdir protractor` to the Docker file.
